### ISSUE TITLE
Compatibility with Matomo 4

### ISSUE THREAD

**Issue by luskin72** [patrickbr/piwik-LoginFailLog#6]
Hi!

Can you make the plugin compatible with Matomo 4?
It will be MUCH appreciated!

**Comment by lcuis** [comment]
Hello!

Indeed, I also see the following message in the plugins management page of my Matomo installation:
```
LoginFailLog requires Piwik <4.0.0-b1.
```
It seems to be caused by the following line in the `piwik-LoginFailLog/plugin.json` file:
```
"piwik": ">=3.0.0-b1,<4.0.0-b1"
```
This line gives me the impression of being set arbitrarilly for the upper bound part. I may very well be wrong.

Here is what I did:
1) Downloaded the plugin zip file from https://plugins.matomo.org/LoginFailLog?matomoversion=3
2) Unzipped and changed the upper bound to `5.0.0-b1`
3) Changed the plugin version number to `0.1.2`
4) Temporarilly allowed manual plugin upload by adding `enable_plugin_upload = 1` in the `[General]` section of the server `config.ini.php` file
5) Zipped, uploaded, installed and activated the plugin from the Matomo plugins management page
6) Deactivated the manual plugin upload (by reverting step 4) for security reasons
7) Tested a wrong login attempt from a VPN connection

I got the following line in the logs:
```
WARNING LoginFailLog[2020-12-30 03:22:33 UTC] [9946a] Failed login from 123.45.67.89 with username 'testing'.
```

=> success

**Comment by lcuis** [comment]
Here is a PR with this modest adaptation:
https://github.com/patrickbr/piwik-LoginFailLog/pull/7

**Comment by lcuis** [comment]
[LoginFailLog-0.1.2.zip](https://github.com/patrickbr/piwik-LoginFailLog/files/5752977/LoginFailLog-0.1.2.zip)
Also, in case this helps, here is the zip file I used for my tests.

**Comment by patrickbr** [comment]
Thank you again for your investigation and PR.
